FROM armhf/alpine:edge

RUN apk add --no-cache collectd

RUN apk add --no-cache collectd-network collectd-disk collectd-sensors collectd-dns collectd-ping

#RUN apk add --no-cache libpcap

RUN apk add --no-cache tcpdump

ENTRYPOINT ["/usr/sbin/collectd", "-f"]

